source "https://rubygems.org"
gem "jbuilder", "~> 2.0"
gem "jquery-rails"
gem "mysql2"
gem "rails", "4.2.0"
gem "sdoc", "~> 0.4.0", group: :doc
gem "turbolinks"
gem "twitter-bootstrap-rails", "~> 3.2.0"
gem "uglifier", ">= 1.3.0"

group :development, :test do
  gem "byebug"
  gem "spring"
  gem "web-console", "~> 2.0"
end

